# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-29 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import djorm_pgarray.fields
import tenant_schemas.postgresql_backend.base


class Migration(migrations.Migration):

    # replaces = [(b'customers', '0001_initial'), (b'customers', '0002_auto_20150321_1751'), (b'customers', '0003_customer_default_vendor_kind'), (b'customers', '0004_customer_is_public_instance'), (b'customers', '0005_auto_20160505_1718'), (b'customers', '0006_auto_20160509_1916'), (b'customers', '0007_auto_20160512_0556'), (b'customers', '0006_auto_20160509_1051'), (b'customers', '0008_merge'), (b'customers', '0009_auto_20160515_0602'), (b'customers', '0010_auto_20160515_0611'), (b'customers', '0011_customer_description'), (b'customers', '0012_customer_background'), (b'customers', '0013_auto_20160617_1845'), (b'customers', '0014_customer_direct_signup'), (b'customers', '0015_customer_about_page_guide')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='company name')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('email_domain', models.CharField(blank=True, max_length=127, null=True)),
                ('email', models.EmailField(max_length=75, unique=True, verbose_name='admin email address')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=b'images/logo/', verbose_name='company logo')),
                ('uniqueness', models.BooleanField(default=True)),
                ('features', djorm_pgarray.fields.SmallIntegerArrayField(dbtype=b'smallint', default=[])),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Full name')),
                ('company', models.CharField(max_length=255, verbose_name='Company name')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('website', models.URLField(blank=True, max_length=255, null=True, verbose_name='Website')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact number')),
                ('notes', models.TextField(blank=True, default=b'', max_length=2047, null=True, verbose_name='Notes ')),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set([('schema_name', 'uniqueness')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='schema_name',
            field=models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name]),
        ),
        migrations.AddField(
            model_name='customer',
            name='default_vendor_kind',
            field=models.PositiveSmallIntegerField(choices=[(1, b'preferred'), (2, b'approved'), (3, b'prospective')], default=2),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_public_instance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='weight_clients',
            field=models.FloatField(default=30, help_text=b"Contract billings and durations weighed by client's annual revenue", verbose_name=b'Client Score'),
        ),
        migrations.AddField(
            model_name='customer',
            name='weight_feedback',
            field=models.FloatField(default=10, help_text=b'Feedback scores', verbose_name=b'Feedback Score'),
        ),
        migrations.AddField(
            model_name='customer',
            name='weight_industry',
            field=models.FloatField(default=30, help_text=b'Contract billings among peers', verbose_name=b'Industry Score'),
        ),
        migrations.AddField(
            model_name='customer',
            name='weight_market',
            field=models.FloatField(default=20, help_text=b'Market cap and annual revenue', verbose_name=b'Market Score'),
        ),
        migrations.AddField(
            model_name='customer',
            name='weight_web',
            field=models.FloatField(default=10, help_text=b'Google Pagerank, Alexa Rank, Twitter Followers', verbose_name=b'Web Score'),
        ),
        migrations.AddField(
            model_name='customer',
            name='invoice_limit',
            field=models.PositiveIntegerField(default=5, help_text=b'How many invoices can a vendor upload before charging'),
        ),
        migrations.AddField(
            model_name='customer',
            name='monthly_plan',
            field=models.CharField(choices=[(b'monthly-10', b'$10/month'), (b'monthly-20', b'$20/month'), (b'monthly-50', b'$50/month'), (b'monthly-100', b'$100/month')], default=b'monthly-50', help_text=b'How much to charge vendors of this community', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='admin email address'),
        ),
        migrations.AddField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to=b'images/background/', verbose_name='background'),
        ),
        migrations.AddField(
            model_name='customer',
            name='about_page_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='about_page_video',
            field=models.URLField(blank=True, default=b'', max_length=255, verbose_name='YouTube video'),
        ),
        migrations.AddField(
            model_name='customer',
            name='direct_signup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='about_page_guide',
            field=models.FileField(blank=True, null=True, upload_to=b'images/logo/', verbose_name='How To Guide'),
        ),
    ]
