# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-07 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customerconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='admin email address'),
        ),
    ]
