# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 14:35
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_categorytype_vendor_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytype',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=256, populate_from=b'label', unique=True),
        ),
        migrations.AlterField(
            model_name='skilllevel',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=256, populate_from=b'label', unique=True),
        ),
    ]
