#!/usr/bin/env python

import os

CSS_ROOT = os.path.abspath('med_social/static/css/');

dupes = []
less = {}


for root, dirs, files in os.walk(CSS_ROOT):
    for f in files:
        if f.endswith('.less'):
           less[f.split('.less')[0]] = True
    for f in files:
        if f.endswith('.css') and less.get(f.split('.css')[0]):
            dupes.append(os.path.join(root,f))

for f in dupes:
    os.system('git reset %s' % os.path.relpath(f));
