from django.conf.urls import patterns, url, include

from med_social.decorators import (client_required, member_required)

from . import views

# namespace = vendors
urlpatterns = [
    url(r'^invoices/$', member_required(views.invoice_list), name='invoice_list'),
    url(r'^invoices/(?P<slug>[\w-]+)/$', member_required(views.invoice_list), name='invoice_list'),
    url(r'^invoices/(?P<slug>[\w-]+)/(?P<ref_pk>\d+)/$', member_required(views.invoice_list), name='invoice_list'),

    url(r'^$', views.vendor_list_view, name='list'),
    url(r'^list/$', views.vendor_public_list_view, name='public_list'),
    url(r'^claims/$', views.vendor_claims, name='vendor_claims'),
    url(r'^claims/(?P<pk>\d+)/approve/$', views.vendor_claim_approve, name='vendor_claim_approve'),
    url(r'^claims/(?P<pk>\d+)/reject/$', views.vendor_claim_reject, name='vendor_claim_reject'),
    url(r'^shortlist/$', views.shortlist, name='shortlist'),
    url(r'^shortlist/(?P<slug>[\w-]+)/add/$', views.shortlist_add, name='shortlist_add'),
    url(r'^shortlist/(?P<slug>[\w-]+)/remove/$', views.shortlist_remove, name='shortlist_remove'),
    url(r'^(?P<pk>\d+)/contact_information/$', client_required(views.ContactInformation.as_view()), name='contact_information'),
    url(r'^search/$', client_required(views.VendorSearch.as_view()), name='search'),
    url(r'^recommendations/$', client_required(views.VendorRecommendations.as_view()),
        name='recommendations'),
    url(r'^apply/$', views.VendorApplication.as_view(), name='application'),
    url(r'^invite/$', client_required(views.vendor_invite_view), name='invite'),
    url(r'^(?P<pk>\d+)/$', views.vendor_detail_view_redirect, name='detail'),
    url(r'^clients/$', views.ClientsList.as_view(), name='clients_list'),
    url(r'^(?P<pk>\d+)/clients/$', views.client_list_redirect, name='client_list'),
    url(r'^(?P<pk>\d+)/modal/$', member_required(views.VendorModalDetail.as_view()), name='modal'),
    url(r'^(?P<pk>\d+)/status/$', client_required(views.VendorStatusUpdate.as_view()), name='update_status'),
    url(r'^location/', include('vendors.locations_urls', namespace='locations')),
    url(r'^role/', include('vendors.roles_urls', namespace='roles')),
    url(r'^category/', include('vendors.categories_urls', namespace='categories')),
    url(r'^service/', include('vendors.services_urls', namespace='services')),
    url(r'^industries/', include('vendors.industries_urls', namespace='industries')),
    url(r'^procurement/', include('vendors.procurement_urls', namespace='procurement')),
    url(r'^diversity/', include('vendors.diversity_urls', namespace='diversity')),
    url(r'^(?P<pk>\d+)/procurement/create', client_required(views.ProcurementAdd.as_view()), name='procurement_add'),
    url(r'^(?P<pk>\d+)/procurement/(?P<obj_pk>\d+)/delete', client_required(views.ProcurementDelete.as_view()), name='procurement_delete'),
    url(r'^(?P<pk>\d+)/projects/add/', member_required(views.AddPortfolioItem.as_view()), name='add_portfolio'),
    url(r'^(?P<pk>\d+)/projects/edit', member_required(views.EditPortfolioItem.as_view()), name='edit_portfolio'),
    url(r'^projects/(?P<pk>\d+)/delete/', member_required(views.DeletePortfolioItem.as_view()), name='delete_portfolio'),
    url(r'^(?P<pk>\d+)/engage/edit', client_required(views.VendorEngageEdit.as_view()), name='engage_edit'),
    url(r'^(?P<pk>\d+)/archive', client_required(views.VendorArchive.as_view()), name='archive_vendor'),
    url(r'^(?P<pk>\d+)/skills/', member_required(views.VendorSkillsModal.as_view()), name='skill_list'),
    url(r'^(?P<pk>\d+)/roles/', member_required(views.VendorRolesModal.as_view()), name='role_list'),
    url(r'^(?P<pk>\d+)/services/', member_required(views.VendorServicesModal.as_view()), name='service_list'),
    url(r'^(?P<pk>\d+)/projects/', member_required(views.PortfolioList.as_view()), name='portfolio'),
    url(r'^(?P<pk>\d+)/kind_change/', client_required(views.vendor_kind_change), name='kind_change'),
    url(r'^(?P<pk>\d+)/certs/add/$', member_required(views.CertAdd.as_view()), name='cert_add'),
    url(r'^(?P<pk>\d+)/certs/confirm/(?P<token>\w+)/$', views.CertConfirm.as_view(), name='cert_confirm'),
    url(r'^(?P<pk>\d+)/certs/delete/$', member_required(views.DeleteVendorCert.as_view()), name='cert_delete'),
    url(r'^(?P<pk>\d+)/insurance/add/$', member_required(views.InsuranceAdd.as_view()), name='insurance_add'),
    url(r'^(?P<pk>\d+)/insurance/confirm/(?P<token>\w+)/$', views.InsuranceConfirm.as_view(), name='insurance_confirm'),
    url(r'^(?P<pk>\d+)/insurance/delete/$', member_required(views.InsuranceDelete.as_view()), name='insurance_delete'),
    url(r'^(?P<pk>\d+)/clients/add/$', member_required(views.ClientAdd.as_view()), name='client_add'),
    url(r'^(?P<pk>\d+)/clients/add/new/$', member_required(views.NewClientAdd.as_view()), name='new_client_add'),
    url(r'^(?P<pk>\d+)/(?P<ref_pk>\d+)/clients/added/$', member_required(views.ClientAdded.as_view()), name='client_added'),
    url(r'^(?P<vendor_pk>\d+)/(?P<reference_pk>\d+)/invoice/$', member_required(views.client_invoice_add),
        name='client_invoice_add'),
    # url(r'^(?P<vendor_pk>\d+)/premium/$', member_required(views.premium_subscribe), name='premium_subscribe'),
    url(r'^(?P<pk>\d+)/(?P<ref_pk>\d+)/invoice/(?P<inv_pk>\d+)/verify/$', member_required(views.client_invoice_verify),
        name='client_invoice_verify'),
    url(r'^(?P<pk>\d+)/(?P<ref_pk>\d+)/invoice/(?P<inv_pk>\d+)/edit/$', member_required(views.client_invoice_edit), name='client_invoice_edit'),
    url(r'^(?P<pk>\d+)/(?P<ref_pk>\d+)/invoice/(?P<inv_pk>\d+)/delete/$', member_required(views.client_invoice_delete), name='client_invoice_delete'),
    url(r'^(?P<pk>\d+)/(?P<ref_pk>\d+)/invoice/approve-all/$', member_required(views.client_invoice_approve_all),
        name='client_invoice_approve_all'),
    url(r'^(?P<pk>\d+)/url_verify', views.client_reference_url_verify,
        name='client_reference_url_verify'),
    url(r'^(?P<pk>\d+)/url_remove', views.client_reference_url_delete,
        name='client_reference_url_delete'),
    url(r'^(?P<pk>\d+)/clients/reference/update/$', member_required(views.ClientReferenceUpdate.as_view()), name='client_ref_update'),
    url(r'^(?P<pk>\d+)/clients/confirm/(?P<token>\w+)/$', views.ClientConfirm.as_view(), name='client_confirm'),
    url(r'^(?P<pk>\d+)/clients/delete/$', member_required(views.DeleteClient.as_view()), name='client_delete'),
    url(r'^(?P<pk>\d+)/clients/(?P<cid>\d+)/resend/$', member_required(views.ClientRequestResend.as_view()), name='client_request_resend'),
    url(r'^export/$', client_required(views.vendor_export), name='export_data'),
    url(r'^(?P<pk>\d+)/clients/(?P<cid>\d+)/edit/$', member_required(views.ClientEdit.as_view()), name='client_edit'),
    url(r'^(?P<pk>\d+)/client/thanks/$', views.ClientConfirmThanks.as_view(), name='client_thanks'),
    url(r'^client/learnmore/$', views.LearnMore.as_view(), name='learn_more'),
    url(r'^(?P<pk>\d+)/edit/logo/$', member_required(views.VendorProfileLogoEdit.as_view()), name='edit_logo'),
    url(r'^(?P<pk>\d+)/edit/brochure/$', member_required(views.VendorProfileBrochureEdit.as_view()), name='edit_brochure'),
    url(r'^(?P<pk>\d+)/procurement_link/', client_required(views.VendorProcurementLink.as_view()), name='procurement_link'),
    url(r'^(?P<pk>\d+)/reviews/$', member_required(views.VendorReviews.as_view()), name='reviews'),
    url(r'^(?P<slug>[\w-]+)/claim/$', views.claim_vendor, name='claim_vendor'),
    url(r'^(?P<slug>[\w-]+)/clients/$', member_required(views.ClientList.as_view()), name='client_list_new'),
    url(r'^(?P<slug>[\w-]+)/clients/(?P<ref_pk>\d+)/$', views.view_client, name='client_view'),
    url(r'^(?P<category>[\w-]+)/(?P<slug>[\w-]+)/clients/$', member_required(views.ClientList.as_view()), name='client_list_new'),
    url(r'^(?P<category>[\w-]+)/(?P<slug>[\w-]+)/clients/(?P<ref_pk>\d+)/$', views.view_client, name='client_view'),
    url(r'^(?P<slug>[\w-]+)/$', views.vendor_detail_view, name='detail_new'),
    url(r'^(?P<category>[\w-]+)/(?P<slug>[\w-]+)/$', views.vendor_detail_view, name='detail_new'),
]
