# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import storages.backends.s3boto
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20160523_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.FileField(null=True, storage=storages.backends.s3boto.S3BotoStorage(acl=b'private', bucket=b'dev-proven-cc', querystring_auth=True, querystring_expire=600), upload_to=users.models._get_resume_upload_path),
        ),
    ]
