# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20160615_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_invited',
            field=models.BooleanField(default=True),
        ),
    ]
