# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_user_is_invited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_invited',
        ),
        migrations.AddField(
            model_name='signuptoken',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signuptoken',
            name='is_invited',
            field=models.BooleanField(default=False),
        ),
    ]
