# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20160622_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuptoken',
            name='first_name',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='signuptoken',
            name='last_name',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='last name'),
        ),
    ]
