# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20160622_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuptoken',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signuptoken',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='last name'),
            preserve_default=False,
        ),
    ]
