# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_squashed_0015_customer_about_page_guide'),
        ('users', '0036_auto_20160622_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='communities',
            field=models.ManyToManyField(blank=True, related_name='users', to='customers.Customer'),
        ),
    ]
