# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_user_communities'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=68)),
                ('description', models.TextField()),
                ('keywords', models.TextField()),
            ],
        ),
    ]
