# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_seometadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seometadata',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='seometadata',
            name='keywords',
            field=models.TextField(blank=True),
        ),
    ]
