# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-29 22:40
from __future__ import unicode_literals

import autoslug.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_pgjson.fields
import phonenumber_field.modelfields
import picklefield.fields
import uuid
import uuidfield.fields
import vendors.models


def merge_services_skills(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    VendorCategories = apps.get_model("vendors", "VendorCategories")
    VendorServices = apps.get_model("vendors", "VendorServices")
    Category = apps.get_model("categories", "Category")

    for obj in VendorServices.objects.all():
        slug = obj.service.slug
        vendor = obj.vendor
        service = obj.service
        categ = Category.objects.filter(slug=slug, kind=Category.KIND_SKILL).first()
        if not categ:
            categ = Category.objects.create(name=service.name, kind=Category.KIND_SKILL)
        VendorCategories.objects.get_or_create(vendor=vendor, skill=categ)
        obj.delete()


def nothing(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    # replaces = [(b'vendors', '0041_auto_20150714_1026'), (b'vendors', '0042_auto_20150715_1431'), (b'vendors', '0043_auto_20150803_0838'), (b'vendors', '0044_auto_20150805_1144'), (b'vendors', '0045_auto_20150813_1002'), (b'vendors', '0046_auto_20150901_2016'), (b'vendors', '0047_auto_20150904_1520'), (b'vendors', '0048_auto_20150910_0721'), (b'vendors', '0049_auto_20150917_1159'), (b'vendors', '0050_auto_20150917_1445'), (b'vendors', '0051_auto_20150924_0831'), (b'vendors', '0052_auto_20150925_1321'), (b'vendors', '0053_auto_20150930_1205'), (b'vendors', '0054_auto_20151015_0742'), (b'vendors', '0055_auto_20151015_0855'), (b'vendors', '0056_auto_20151210_1055'), (b'vendors', '0057_auto_20151214_1038'), (b'vendors', '0058_auto_20151215_0518'), (b'vendors', '0059_vendor_tin'), (b'vendors', '0060_vendor_duns'), (b'vendors', '0061_auto_20160324_1744'), (b'vendors', '0062_auto_20160324_2329'), (b'vendors', '0063_auto_20160324_2351'), (b'vendors', '0064_auto_20160325_0024'), (b'vendors', '0065_auto_20160325_0156'), (b'vendors', '0066_clientqueue'), (b'vendors', '0067_auto_20160330_1212'), (b'vendors', '0068_clientreference_invoice_verification'), (b'vendors', '0069_auto_20160331_0101'), (b'vendors', '0070_auto_20160404_1155'), (b'vendors', '0071_auto_20160405_0521')]

    dependencies = [
        ('categories', '0006_categorytype_vendor_editable'),
        ('vendors', '0040_auto_20150712_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='custom_categories',
            field=models.ManyToManyField(related_name='vendor_custom', through='vendors.VendorCustomKind', to=b'categories.Category'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.TextField(default=b''),
        ),
        migrations.RunPython(
            code=merge_services_skills,
            reverse_code=nothing,
        ),
        migrations.AlterField(
            model_name='clientreference',
            name='last_sent',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.PositiveSmallIntegerField(choices=[(1, b'Review'), (2, b'Client'), (3, b'Profile')])),
                ('score', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=6)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_obj', to='vendors.Vendor')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set([('kind', 'vendor')]),
        ),
        migrations.AlterModelOptions(
            name='vendorlocation',
            options={'ordering': ('-num_resources', 'location')},
        ),
        migrations.AddField(
            model_name='vendorcustomkind',
            name='primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorcustomkind',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='custom_categories',
            field=models.ManyToManyField(related_name='vendors_custom', through='vendors.VendorCustomKind', to=b'categories.Category'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='score',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vendorcustomkind',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_kind_obj', to='categories.Category'),
        ),
        migrations.CreateModel(
            name='ProcurementLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default=b'')),
                ('url', models.URLField(blank=True, default=b'')),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_link', to='vendors.Vendor')),
            ],
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vendorinvitation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_vendor_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='KindLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=256, unique=True)),
                ('kind', models.PositiveSmallIntegerField(choices=[(1, b'preferred'), (2, b'approved'), (3, b'prospective')], unique=True)),
                ('description', models.CharField(blank=True, default=b'', max_length=200)),
                ('show_label', models.BooleanField(default=True)),
                ('filter_default', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.PositiveSmallIntegerField(choices=[(1, b'Ownership'), (2, b'Employees')])),
                ('label', models.CharField(max_length=256, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=256, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='vendor',
            name='diversity',
            field=models.ManyToManyField(related_name='diversity', to=b'vendors.Diversity'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='meta',
            field=django_pgjson.fields.JsonBField(blank=True, default=vendors.models._default_vendor_meta),
        ),
        migrations.AddField(
            model_name='vendor',
            name='has_onboarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='score',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Review'), (2, b'Client'), (3, b'Profile'), (4, b'Project'), (5, b'VendorKind')]),
        ),
        migrations.CreateModel(
            name='VendorWhois',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, default=b'', max_length=254)),
                ('email', models.EmailField(blank=True, max_length=75, null=True)),
                ('registrant', models.CharField(blank=True, max_length=254, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('expires_on', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=254, null=True)),
                ('social_handles', django_pgjson.fields.JsonBField(blank=True, default=vendors.models.default_json)),
                ('metrics', django_pgjson.fields.JsonBField(blank=True, default=vendors.models.default_json)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whois', to='vendors.Vendor')),
            ],
        ),
        migrations.AddField(
            model_name='vendor',
            name='verifications',
            field=django_pgjson.fields.JsonBField(blank=True, default=vendors.models._default_vendor_meta),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tin',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='duns',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='certverification',
            name='since',
            field=models.IntegerField(choices=[(2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980), (1979, 1979), (1978, 1978), (1977, 1977), (1976, 1976), (1975, 1975), (1974, 1974), (1973, 1973), (1972, 1972), (1971, 1971), (1970, 1970), (1969, 1969), (1968, 1968), (1967, 1967), (1966, 1966), (1965, 1965), (1964, 1964), (1963, 1963), (1962, 1962), (1961, 1961), (1960, 1960), (1959, 1959), (1958, 1958), (1957, 1957), (1956, 1956), (1955, 1955), (1954, 1954), (1953, 1953), (1952, 1952), (1951, 1951), (1950, 1950), (1949, 1949), (1948, 1948), (1947, 1947), (1946, 1946), (1945, 1945), (1944, 1944), (1943, 1943), (1942, 1942), (1941, 1941), (1940, 1940), (1939, 1939), (1938, 1938), (1937, 1937), (1936, 1936), (1935, 1935), (1934, 1934), (1933, 1933), (1932, 1932), (1931, 1931), (1930, 1930), (1929, 1929), (1928, 1928), (1927, 1927), (1926, 1926), (1925, 1925), (1924, 1924), (1923, 1923), (1922, 1922), (1921, 1921), (1920, 1920), (1919, 1919), (1918, 1918), (1917, 1917), (1916, 1916), (1915, 1915), (1914, 1914), (1913, 1913), (1912, 1912), (1911, 1911), (1910, 1910), (1909, 1909), (1908, 1908), (1907, 1907), (1906, 1906), (1905, 1905), (1904, 1904), (1903, 1903), (1902, 1902), (1901, 1901), (1900, 1900)], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='founded',
            field=models.IntegerField(blank=True, choices=[(2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980), (1979, 1979), (1978, 1978), (1977, 1977), (1976, 1976), (1975, 1975), (1974, 1974), (1973, 1973), (1972, 1972), (1971, 1971), (1970, 1970), (1969, 1969), (1968, 1968), (1967, 1967), (1966, 1966), (1965, 1965), (1964, 1964), (1963, 1963), (1962, 1962), (1961, 1961), (1960, 1960), (1959, 1959), (1958, 1958), (1957, 1957), (1956, 1956), (1955, 1955), (1954, 1954), (1953, 1953), (1952, 1952), (1951, 1951), (1950, 1950), (1949, 1949), (1948, 1948), (1947, 1947), (1946, 1946), (1945, 1945), (1944, 1944), (1943, 1943), (1942, 1942), (1941, 1941), (1940, 1940), (1939, 1939), (1938, 1938), (1937, 1937), (1936, 1936), (1935, 1935), (1934, 1934), (1933, 1933), (1932, 1932), (1931, 1931), (1930, 1930), (1929, 1929), (1928, 1928), (1927, 1927), (1926, 1926), (1925, 1925), (1924, 1924), (1923, 1923), (1922, 1922), (1921, 1921), (1920, 1920), (1919, 1919), (1918, 1918), (1917, 1917), (1916, 1916), (1915, 1915), (1914, 1914), (1913, 1913), (1912, 1912), (1911, 1911), (1910, 1910), (1909, 1909), (1908, 1908), (1907, 1907), (1906, 1906), (1905, 1905), (1904, 1904), (1903, 1903), (1902, 1902), (1901, 1901), (1900, 1900)], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(1, b'preferred'), (2, b'approved'), (3, b'prospective')], default=3),
        ),
        migrations.AddField(
            model_name='vendor',
            name='alexa_rank',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=b'Alexa Rank'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='annual_revenue',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='clearbit_data',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='employee_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=b'Employee Count'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='founded_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='google_pagerank',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=b'Google PageRank'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='market_cap',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='proven_score',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True, verbose_name=b'Proven Score'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='registration_type',
            field=models.CharField(blank=True, choices=[(b'public', b'Public'), (b'private', b'Private')], max_length=100, verbose_name=b'Registration Type'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='twitter_followers',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=b'Twitter Followers'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='client_score',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True, verbose_name=b'Client Score'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='company_score',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True, verbose_name=b'Company Score'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='potential_client_score',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True, verbose_name=b'Potential Client Score'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='potential_proven_score',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True, verbose_name=b'Potential Proven Score'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='web_score',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True, verbose_name=b'Web Score'),
        ),
        migrations.CreateModel(
            name='ClientQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=75, verbose_name='Your Email')),
                ('notes', models.TextField(blank=True, verbose_name='More Information')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.FileField(blank=True, null=True, upload_to=b'client-invoices')),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('invoice_date_start', models.DateField(null=True)),
                ('invoice_date_end', models.DateField(blank=True, null=True)),
                ('date_verified', models.DateTimeField(blank=True, null=True)),
                ('uuid', uuidfield.fields.UUIDField(default=uuid.uuid4, editable=False, max_length=32)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateTimeField(blank=True, editable=False, null=True)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='vendors.ClientReference')),
                ('invoice_duration', models.IntegerField(choices=[(1, b'1 day+'), (7, b'1 week+'), (30, b'1 month+'), (90, b'3 months+'), (180, b'6 months+'), (360, b'1 year+'), (540, b'1.5 years+'), (720, b'2 years+'), (1080, b'3 years+'), (1440, b'4 years+'), (1800, b'5 years+')], null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='clientqueue',
            options={'ordering': ('-created_on',), 'verbose_name': 'Community Request', 'verbose_name_plural': 'Community Requests'},
        ),
        migrations.AddField(
            model_name='clientreference',
            name='invoice_verification',
            field=models.BooleanField(default=False),
        ),
    ]
