# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 14:35
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0082_auto_20160515_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diversity',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=256, populate_from='label', unique=True),
        ),
        migrations.AlterField(
            model_name='kindlabel',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=256, populate_from='label', unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
