# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0084_vendorclaim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorclaim',
            name='approved',
            field=models.NullBooleanField(),
        ),
    ]
