# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0085_auto_20160524_1859'),
        ('vendors', '0084_auto_20160526_1220'),
    ]

    operations = [
    ]
