# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 15:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0086_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorclaim',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='vendorclaim',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendorclaim',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendorclaim',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vendorclaim',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_claims', to=settings.AUTH_USER_MODEL),
        ),
    ]
