# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0087_auto_20160530_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorclaim',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='vendorclaim',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vendorclaim',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
