# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0088_auto_20160530_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorcustomkind',
            options={'ordering': ('-primary', '-allocation')},
        ),
    ]
