# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0090_auto_20160610_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='background',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=b'images/background/', verbose_name='Company background image'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='diversity',
            field=models.ManyToManyField(blank=True, related_name='diversity', to='vendors.Diversity'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='duns',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='kind',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'preferred'), (2, b'approved'), (3, b'prospective')], default=3),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='tin',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
