# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0091_auto_20160611_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='open_for_business',
            field=models.BooleanField(default=True),
        ),
    ]
