# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0092_vendor_open_for_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='open_for_business',
            field=models.BooleanField(default=False),
        ),
    ]
