# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0094_auto_20160613_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientreference',
            name='billing_new',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '<$1k'), (2, '$5K - $10K'), (3, '$10K - $20K'), (4, '$20K - $50K'), (5, '$50K - $100K'), (6, '$100K - $500K'), (7, '$500K - $1M'), (8, '$1M - $5M'), (9, '$5M - $10M'), (10, '$10M - $50M'), (11, '$50M+')], null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Invoice Amount'),
        ),
    ]
