# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0095_auto_20160620_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ('-open_for_business', '-proven_score')},
        ),
        migrations.AlterField(
            model_name='clientreference',
            name='billing_new',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '<$1k'), (2, '$1K - $5K'), (3, '$5K - $10K'), (4, '$10K - $20K'), (5, '$20K - $50K'), (6, '$50K - $100K'), (7, '$100K - $500K'), (8, '$500K - $1M'), (9, '$1M - $5M'), (10, '$5M - $10M'), (11, '$10M - $50M'), (12, '$50M+')], null=True),
        ),
    ]
