# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 00:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0096_auto_20160622_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinvitation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
