# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0100_auto_20160701_0301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('date_verified', '-date_created')},
        ),
        migrations.AddField(
            model_name='clientreference',
            name='proof_url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
    ]
