# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-06 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0102_auto_20160903_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='linkedin',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Linkedin'),
        ),
    ]
