# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-10 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0104_auto_20160908_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='sync_clearbit',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Synced with clearbit'),
        ),
    ]
