# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-18 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0105_auto_20160910_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientreference',
            name='is_verified',
        ),
    ]
