# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 14:35
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20160325_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, null=True, populate_from=b'name', unique=True),
        ),
    ]
