# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 14:35
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20151012_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=b'name', unique_with=[b'content_type']),
        ),
    ]
